language: node_js
node_js:
  - "12.7.0"

before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test:coverage
    - stage: security
      if: branch = master
      script: snyk test

deploy:
  on:
    branch: master
  provider: npm
  email: $NPM_PUBLISH_EMAIL
  api_key: $NPM_TOKEN

notifications:
  email:
    - $NPM_PUBLISH_EMAIL
  slack:
    rooms:
      - diego-qsg3460:bjoicwRP22vx7c9KRzyAMoAF#builds
